name: favorite
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  provider: ^4.1.1
  image_picker: ^0.6.6+1
  path_provider: ^1.6.8
  path: ^1.6.4
  sqflite: ^1.3.0+1
  location: ^3.0.2
  google_maps_flutter: ^0.5.27+2
  http: ^0.12.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.7.5

flutter_icons:
  android: true
  ios: true
  image_path: "dev_assets/places.png"
  adaptive_icon_background: "#191919"
  adaptive_icon_foreground: "dev_assets/places-adaptive.png"

flutter:
  uses-material-design: true
